### ISSUE TITLE
using semver

### ISSUE THREAD

**Issue by noamokman** [fortywinkz/load-gulp-tasks#1]
Hi there!
Just wanted to use your package when I noticed you are not using [semver](http://semver.org/).
Do you mind updating to version 1.0.0.
Thanks :+1:

**Comment by yurii-sorokin** [comment]
Hello, @noamokman. Sorry for not replying sooner. I don't mind to update it at all. The only difference I will increment the minor version to meet semver specification:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

I hope it's suitable for you.
